version: '3'

services:
  node:
    build: .
    image: gw2trivia-node:${GW2TRIVIA_VERSION:-latest}
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - proxy
      - default
      - gw2trivia_bridge
    volumes:
      - ./${NODE_ENV:-production}/filestore:/usr/src/app/filestore
      - /usr/src/app/node_modules
    ports:
      - ${NODE_PORT:-3000}:3000
      - ${NODE_DEBUGGER_PORT:-9229}:9229
    env_file:
      - .env.${NODE_ENV:-production}
    command: npm start

  postgres:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - default
      - gw2trivia_bridge
    volumes:
      - ./${NODE_ENV:-production}/db/postgresql:/var/lib/postgresql
      - ./${NODE_ENV:-production}/db/postgresql/data:/var/lib/postgresql/data
      - ./${NODE_ENV:-production}/db/initdb:/docker-entrypoint-initdb.d/
    env_file:
      - .env.${NODE_ENV:-production}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
networks:
  proxy:
    external: true
  gw2trivia_bridge:
    name: gw2trivia_${NODE_ENV:-production}_bridge
    external: true
